import { RiskHotspot, RiskLevel, DayForecast } from '../types';

/**
 * Complete List of 77 Risk Hotspots across Nagpur City and Metropolitan Area.
 * Mapped to NMC 10 Zones, major nallahs (Nag River, Pili River, Pora River),
 * low-lying underpasses, flyover junctions, and suburban catchments.
 */
export const NAGPUR_77_HOTSPOTS: RiskHotspot[] = [
  // 1-10: Nag River Catchment & Ambazari Overflow Belt
  {
    id: 'HOT-01',
    name: 'Ambazari Lake Overflow Discharge Channel & Slum Belt',
    marathiName: 'अंबाजारी तलाव ओव्हरफ्लो नाला व झोपडपट्टी परिसर',
    zone: 'Dharampeth (Zone 2)',
    wardNo: 'Ward 12',
    lat: 21.1298,
    lng: 79.0435,
    category: 'Reservoir / Canal Discharge',
    baseRisk: 'severe',
    elevationMeters: 308,
    vulnerabilityFactor: 'Direct sluice gate overflow and low embankment wall along Krazy Castle road',
    historicalEvent: 'September 2023 massive flash flood (3,500+ homes inundated)',
    drainageCapacity: '65% of peak discharge',
    nearestNDRFPost: 'VNIT Disaster Sub-Station (1.2 km)',
    emergencyHelpline: '0712-2567011',
    nodalContact: 'Shri Rajesh Sharma (EE Dharampeth)',
    evacuationShelter: 'VNIT Community Hall & Ambazari Municipal School',
    populationImpactedEstimate: 8500,
    liveWaterLevelCm: 142,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-02',
    name: 'Nag River Bank - Shankar Nagar Bridge & Daga Layout',
    marathiName: 'नाग नदी काठ - शंकर नगर पूल व डागा लेआउट',
    zone: 'Dharampeth (Zone 2)',
    wardNo: 'Ward 14',
    lat: 21.1378,
    lng: 79.0612,
    category: 'River / Waterbody Overflow',
    baseRisk: 'severe',
    elevationMeters: 306,
    vulnerabilityFactor: 'Narrow bridge piers catching river debris causing backwater accumulation',
    historicalEvent: 'Submerged basement parking & ground floor residences in 2023 monsoon',
    drainageCapacity: '70% bottleneck',
    nearestNDRFPost: 'Civil Lines SDRF Camp (2.8 km)',
    emergencyHelpline: '0712-2567012',
    nodalContact: 'Shri Rajesh Sharma (EE Dharampeth)',
    evacuationShelter: 'Shankar Nagar Samaj Bhavan',
    populationImpactedEstimate: 4200,
    liveWaterLevelCm: 110,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-03',
    name: 'Pardi Flyover Junction & Old Bhandara Road Chokepoint',
    marathiName: 'पारडी उड्डाणपूल जंक्शन व जुना भंडारा रोड',
    zone: 'Lakadganj (Zone 8)',
    wardNo: 'Ward 24',
    lat: 21.1492,
    lng: 79.1485,
    category: 'Bridge / Flyover Approach',
    baseRisk: 'severe',
    elevationMeters: 301,
    vulnerabilityFactor: 'Massive storm runoff stagnation under NH-6 flyover pillars & highway ramps',
    historicalEvent: '3 to 4 feet waterlogging blocking inter-state freight transport',
    drainageCapacity: '55% silted box drain',
    nearestNDRFPost: 'Kalamna Fire Station (1.8 km)',
    emergencyHelpline: '0712-2567018',
    nodalContact: 'Smt. Priya Channe (EE Lakadganj)',
    evacuationShelter: 'Pardi Ward Office & ZP High School',
    populationImpactedEstimate: 12000,
    liveWaterLevelCm: 125,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-04',
    name: 'Kalamna Agriculture Produce Market & Railway Siding',
    marathiName: 'कळमना एपीएमसी कृषी बाजार व रेल्वे सायडिंग',
    zone: 'Satranjipura (Zone 7)',
    wardNo: 'Ward 21',
    lat: 21.1712,
    lng: 79.1421,
    category: 'Commercial / Market Drain Choke',
    baseRisk: 'severe',
    elevationMeters: 298,
    vulnerabilityFactor: 'Low-lying wholesale market yard lacking dedicated storm outfall to Pili River',
    historicalEvent: 'Heavy grain & spice spoilage during monsoon cloudbursts',
    drainageCapacity: '48% capacity',
    nearestNDRFPost: 'Kalamna Market Police & Fire Outpost (0.5 km)',
    emergencyHelpline: '0712-2567017',
    nodalContact: 'Shri Dilip Gedam (EE Satranjipura)',
    evacuationShelter: 'APMC Administrative Complex',
    populationImpactedEstimate: 9500,
    liveWaterLevelCm: 98,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-05',
    name: 'Mansar Flood Basin & Pench Canal Confluence',
    marathiName: 'मानसर पूर क्षेत्र व पेंच कालवा संगम',
    zone: 'Rural / Outer Division',
    wardNo: 'Metropolitan Gram Panchayat',
    lat: 21.3982,
    lng: 79.2561,
    category: 'Reservoir / Canal Discharge',
    baseRisk: 'severe',
    elevationMeters: 312,
    vulnerabilityFactor: 'Canal breach risk and flash runoff from Ramtek hill range foothills',
    historicalEvent: 'NH-44 diversion due to gushing culvert overflow in July 2022',
    drainageCapacity: '60%',
    nearestNDRFPost: 'Ramtek Emergency Relief Base (6.5 km)',
    emergencyHelpline: '0712-2567030',
    nodalContact: 'Shri Milind Deshmukh (EE PWD Rural)',
    evacuationShelter: 'Mansar Gram Panchayat Bhawan & Primary Health Centre',
    populationImpactedEstimate: 6200,
    liveWaterLevelCm: 85,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-06',
    name: 'Narendra Nagar Railway Underpass (RUB)',
    marathiName: 'नरेंद्र नगर रेल्वे भुयारी मार्ग (अंडरपास)',
    zone: 'Nehru Nagar (Zone 5)',
    wardNo: 'Ward 33',
    lat: 21.1092,
    lng: 79.0815,
    category: 'Underpass Waterlogging',
    baseRisk: 'severe',
    elevationMeters: 295,
    vulnerabilityFactor: 'Sunken bowl topography where road sits 4.8m below natural ground surface',
    historicalEvent: 'Vehicles trapped under 6 feet water, pumps overloaded during intense showers',
    drainageCapacity: 'De-watering pumps 120 HP',
    nearestNDRFPost: 'Sonegaon Disaster Station (2.1 km)',
    emergencyHelpline: '0712-2567015',
    nodalContact: 'Shri Anand Mankar (EE Nehru Nagar)',
    evacuationShelter: 'Narendra Nagar Garden Hall',
    populationImpactedEstimate: 15000,
    liveWaterLevelCm: 160,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-07',
    name: 'Sitabuldi Munje Chowk & Metro Pier Low Point',
    marathiName: 'सीताबर्डी मुंजे चौक व मेट्रो पिलर जंक्शन',
    zone: 'Dhantoli (Zone 4)',
    wardNo: 'Ward 17',
    lat: 21.1448,
    lng: 79.0832,
    category: 'Commercial / Market Drain Choke',
    baseRisk: 'moderate',
    elevationMeters: 304,
    vulnerabilityFactor: 'Dense pedestrian shopping district with concrete paving obstructing percolation',
    historicalEvent: 'Waterlogging up to 2.5 feet disrupting city bus interchange & market access',
    drainageCapacity: '75%',
    nearestNDRFPost: 'Cotton Market Fire Station (1.1 km)',
    emergencyHelpline: '0712-2567014',
    nodalContact: 'Smt. Kavita Patil (EE Dhantoli)',
    evacuationShelter: 'Sitabuldi Fort Complex & Railway Station Waiting Hall',
    populationImpactedEstimate: 22000,
    liveWaterLevelCm: 45,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-08',
    name: 'Mahal - Badkas Chowk & Kotwali Nallah Depression',
    marathiName: 'महाल - बडकस चौक व कोतवाली नाला क्षेत्र',
    zone: 'Gandhibagh (Zone 6)',
    wardNo: 'Ward 19',
    lat: 21.1442,
    lng: 79.1025,
    category: 'Low-lying Residential',
    baseRisk: 'moderate',
    elevationMeters: 302,
    vulnerabilityFactor: 'Historic dense old city settlement with aged British-era arch masonry storm drains',
    historicalEvent: 'Basement shops and wadas flooded during 50mm/hr rains',
    drainageCapacity: '62%',
    nearestNDRFPost: 'Gandhibagh Fire Station (0.9 km)',
    emergencyHelpline: '0712-2567016',
    nodalContact: 'Shri Sanjay Ingle (EE Gandhibagh)',
    evacuationShelter: 'Town Hall Mahal & CP&Berar College Hall',
    populationImpactedEstimate: 14000,
    liveWaterLevelCm: 55,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-09',
    name: 'Nag River - Panchsheel Square Culvert & Jhansi Rani Chowk',
    marathiName: 'नाग नदी - पंचशील चौक कल्व्हर्ट व झाशी राणी चौक',
    zone: 'Dhantoli (Zone 4)',
    wardNo: 'Ward 16',
    lat: 21.1395,
    lng: 79.0781,
    category: 'River / Waterbody Overflow',
    baseRisk: 'severe',
    elevationMeters: 303,
    vulnerabilityFactor: 'Sharp bend in Nag River causing sudden velocity reduction and silt bank formation',
    historicalEvent: 'Backing up into Panchsheel cinema road and Dhantoli hospitals basement',
    drainageCapacity: '68%',
    nearestNDRFPost: 'Ganeshpeth Central Fire HQ (1.5 km)',
    emergencyHelpline: '0712-2567014',
    nodalContact: 'Smt. Kavita Patil (EE Dhantoli)',
    evacuationShelter: 'Dhantoli Nagrik Mandal Hall',
    populationImpactedEstimate: 7800,
    liveWaterLevelCm: 90,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-10',
    name: 'Besa-Pipla T-Point & Pora River Tributary',
    marathiName: 'बेसा-पिपळा टी-पॉइंट व पोरा नदी उपनाला',
    zone: 'Nehru Nagar (Zone 5 / Southern Outskirts)',
    wardNo: 'Ward 36',
    lat: 21.0852,
    lng: 79.0985,
    category: 'River / Waterbody Overflow',
    baseRisk: 'severe',
    elevationMeters: 297,
    vulnerabilityFactor: 'Rapid real-estate expansion encroaching upon natural drainage wetlands of Pora River',
    historicalEvent: 'Residential towers ground floors marooned for 36 hours in Aug 2024',
    drainageCapacity: '50% under-sized culvert',
    nearestNDRFPost: 'Manewada Sub-Station (2.5 km)',
    emergencyHelpline: '0712-2567015',
    nodalContact: 'Shri Anand Mankar (EE Nehru Nagar)',
    evacuationShelter: 'Besa Gram Panchayat Community Hall',
    populationImpactedEstimate: 16500,
    liveWaterLevelCm: 115,
    cctvStreamAvailable: true,
  },

  // 11-20: Pili River & Northern / Eastern Industrial Slums
  {
    id: 'HOT-11',
    name: 'Pili River - Jaripatka Nallah Bridge & Mecosabagh Lows',
    marathiName: 'पिळी नदी - जरीपटका नाला पूल व मेकोसाबाग',
    zone: 'Mangalwari (Zone 10)',
    wardNo: 'Ward 03',
    lat: 21.1825,
    lng: 79.0895,
    category: 'River / Waterbody Overflow',
    baseRisk: 'severe',
    elevationMeters: 300,
    vulnerabilityFactor: 'Pili river bank overflow encroaching on high-density residential colonies',
    historicalEvent: '1500 families evacuated to higher grounds during continuous 4-hour deluge',
    drainageCapacity: '58%',
    nearestNDRFPost: 'Sugat Nagar Rescue Post (1.4 km)',
    emergencyHelpline: '0712-2567020',
    nodalContact: 'Shri Nitin Bhende (EE Mangalwari)',
    evacuationShelter: 'Dayanand Arya Kanya Vidyalaya Jaripatka',
    populationImpactedEstimate: 11000,
    liveWaterLevelCm: 105,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-12',
    name: 'Pili River - Kamptee Road Bridge & Uppalwadi Industrial Belt',
    marathiName: 'पिळी नदी - कामठी रोड पूल व उप्पलवाडी एमआयडीसी',
    zone: 'Ashi Nagar (Zone 9)',
    wardNo: 'Ward 07',
    lat: 21.1921,
    lng: 79.1185,
    category: 'Industrial / Highway Corridor',
    baseRisk: 'severe',
    elevationMeters: 296,
    vulnerabilityFactor: 'Chemical and packaging industrial units along low river plain with heavy silt runoff',
    historicalEvent: 'Factory floor inundation and hazardous effluent mixing during cloudbursts',
    drainageCapacity: '52%',
    nearestNDRFPost: 'Automotive Square Fire Station (2.0 km)',
    emergencyHelpline: '0712-2567019',
    nodalContact: 'Smt. Vandana Meshram (EE Ashi Nagar)',
    evacuationShelter: 'Uppalwadi Association Hall',
    populationImpactedEstimate: 8000,
    liveWaterLevelCm: 130,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-13',
    name: 'Automotive Square & Ring Road Low-level Dip',
    marathiName: 'ऑटोमोटिव्ह चौक व रिंग रोड खोलगट भाग',
    zone: 'Ashi Nagar (Zone 9)',
    wardNo: 'Ward 08',
    lat: 21.2015,
    lng: 79.1082,
    category: 'Bridge / Flyover Approach',
    baseRisk: 'moderate',
    elevationMeters: 301,
    vulnerabilityFactor: 'Inadequate stormwater cross-culverts connecting North Ring Road to rural drains',
    historicalEvent: 'Traffic jam lasting 5 hours with submerged container trucks',
    drainageCapacity: '65%',
    nearestNDRFPost: 'Automotive Square Post (0.4 km)',
    emergencyHelpline: '0712-2567019',
    nodalContact: 'Smt. Vandana Meshram (EE Ashi Nagar)',
    evacuationShelter: 'NMC Primary Health Centre Ashi Nagar',
    populationImpactedEstimate: 6000,
    liveWaterLevelCm: 50,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-14',
    name: 'Koradi Thermal Power Plant Ash Dam Catchment',
    marathiName: 'कोराडी औष्णिक वीज केंद्र राख धरण परिसर',
    zone: 'Rural / Outer Division (Koradi)',
    wardNo: 'Koradi Sector 4',
    lat: 21.2525,
    lng: 79.0955,
    category: 'Reservoir / Canal Discharge',
    baseRisk: 'moderate',
    elevationMeters: 309,
    vulnerabilityFactor: 'Fly ash slurry pond overflow into local streams during flash rains',
    historicalEvent: 'Breach alert requiring precautionary evacuation of Khasala village',
    drainageCapacity: '72%',
    nearestNDRFPost: 'Koradi Emergency Team (1.0 km)',
    emergencyHelpline: '0712-2567030',
    nodalContact: 'Shri Milind Deshmukh (EE PWD Rural)',
    evacuationShelter: 'Koradi Temple Pilgrims Dharamshala',
    populationImpactedEstimate: 5200,
    liveWaterLevelCm: 40,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-15',
    name: 'Mankapur Sports Complex Ring Road Underpass',
    marathiName: 'मानकापूर इनडोअर स्टेडियम रिंग रोड भुयारी मार्ग',
    zone: 'Mangalwari (Zone 10)',
    wardNo: 'Ward 01',
    lat: 21.1895,
    lng: 79.0762,
    category: 'Underpass Waterlogging',
    baseRisk: 'moderate',
    elevationMeters: 305,
    vulnerabilityFactor: 'Surface runoff gradient from Zingabai Takli plateau into stadium bowl',
    historicalEvent: 'Stadium basement parking submerged up to 4 feet in July 2023',
    drainageCapacity: '70%',
    nearestNDRFPost: 'Koradi Fire Outpost (3.2 km)',
    emergencyHelpline: '0712-2567020',
    nodalContact: 'Shri Nitin Bhende (EE Mangalwari)',
    evacuationShelter: 'Mankapur Indoor Stadium Main Concourse',
    populationImpactedEstimate: 7500,
    liveWaterLevelCm: 60,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-16',
    name: 'Hudkeshwar Old Village & Pora Basin Tributary',
    marathiName: 'हुडकेश्वर जुने गाव व पोरा खोरे नाला',
    zone: 'Hanuman Nagar (Zone 3)',
    wardNo: 'Ward 30',
    lat: 21.0955,
    lng: 79.1215,
    category: 'Slum / Riverbank Settlement',
    baseRisk: 'severe',
    elevationMeters: 294,
    vulnerabilityFactor: 'Unapproved layouts lacking secondary drainage pipelines discharging into open fields',
    historicalEvent: 'Widespread waterlogging reaching waist level in 8 residential colonies',
    drainageCapacity: '40% capacity',
    nearestNDRFPost: 'Sakkardara Fire Station (2.8 km)',
    emergencyHelpline: '0712-2567013',
    nodalContact: 'Shri Suresh Khare (EE Hanuman Nagar)',
    evacuationShelter: 'Hudkeshwar ZP School & Samaj Bhavan',
    populationImpactedEstimate: 14200,
    liveWaterLevelCm: 110,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-17',
    name: 'Manewada Ring Road Square & Cement Road Trench',
    marathiName: 'मानेवाडा रिंग रोड चौक व सिमेंट रस्ता खंदक',
    zone: 'Hanuman Nagar (Zone 3)',
    wardNo: 'Ward 29',
    lat: 21.1045,
    lng: 79.1021,
    category: 'Low-lying Residential',
    baseRisk: 'moderate',
    elevationMeters: 298,
    vulnerabilityFactor: 'Elevated cement concrete road creating a dam effect for adjacent low housing layouts',
    historicalEvent: 'Storm water entering 400+ ground floor houses after 60 min heavy rainfall',
    drainageCapacity: '64%',
    nearestNDRFPost: 'Sakkardara Rescue Base (2.2 km)',
    emergencyHelpline: '0712-2567013',
    nodalContact: 'Shri Suresh Khare (EE Hanuman Nagar)',
    evacuationShelter: 'Manewada High School Ground Hall',
    populationImpactedEstimate: 9800,
    liveWaterLevelCm: 65,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-18',
    name: 'Sakkardara Lake Embankment & Ayurvedic Layout',
    marathiName: 'सक्करदरा तलाव पाळ व आयुर्वेदिक लेआउट',
    zone: 'Nehru Nagar (Zone 5)',
    wardNo: 'Ward 28',
    lat: 21.1215,
    lng: 79.1125,
    category: 'Reservoir / Canal Discharge',
    baseRisk: 'moderate',
    elevationMeters: 300,
    vulnerabilityFactor: 'Lake overflow weir choking on water hyacinth causing embankment seepage',
    historicalEvent: 'Seepage alert along garden wall with road cave-in scare in 2021',
    drainageCapacity: '70%',
    nearestNDRFPost: 'Sakkardara Fire Station (0.6 km)',
    emergencyHelpline: '0712-2567015',
    nodalContact: 'Shri Anand Mankar (EE Nehru Nagar)',
    evacuationShelter: 'Sakkardara Garden Community Pavilion',
    populationImpactedEstimate: 8400,
    liveWaterLevelCm: 50,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-19',
    name: 'Cotton Market - Railway Station Underpass Sub-way',
    marathiName: 'कॉटन मार्केट - रेल्वे स्टेशन सबवे मार्ग',
    zone: 'Dhantoli (Zone 4)',
    wardNo: 'Ward 18',
    lat: 21.1472,
    lng: 79.0915,
    category: 'Underpass Waterlogging',
    baseRisk: 'severe',
    elevationMeters: 297,
    vulnerabilityFactor: 'High silt and organic vegetable waste accumulation clogging sump pit suction filters',
    historicalEvent: 'Subway closed for pedestrians and 2-wheelers due to 5 ft dark stagnant water',
    drainageCapacity: '50%',
    nearestNDRFPost: 'Cotton Market Station (0.2 km)',
    emergencyHelpline: '0712-2567014',
    nodalContact: 'Smt. Kavita Patil (EE Dhantoli)',
    evacuationShelter: 'Railway Retiring Hall & Cotton Market Yard',
    populationImpactedEstimate: 18000,
    liveWaterLevelCm: 135,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-20',
    name: 'Ganeshpeth Bus Stand & Subhash Road Depressions',
    marathiName: 'गणेशपेठ मुख्य बस स्थानक व सुभाष रोड',
    zone: 'Gandhibagh (Zone 6)',
    wardNo: 'Ward 20',
    lat: 21.1412,
    lng: 79.0955,
    category: 'Commercial / Market Drain Choke',
    baseRisk: 'moderate',
    elevationMeters: 301,
    vulnerabilityFactor: 'MSRTC central bus bay surface flooding disrupting state transport schedules',
    historicalEvent: 'Buses stalled in 2.5 ft water near ST terminus exit gate',
    drainageCapacity: '66%',
    nearestNDRFPost: 'Ganeshpeth Fire HQ (0.4 km)',
    emergencyHelpline: '0712-2567016',
    nodalContact: 'Shri Sanjay Ingle (EE Gandhibagh)',
    evacuationShelter: 'Ganeshpeth ST Terminal Multi-storey Building',
    populationImpactedEstimate: 25000,
    liveWaterLevelCm: 55,
    cctvStreamAvailable: true,
  },

  // 21-35: Central, Western & Southern Hotspots
  {
    id: 'HOT-21',
    name: 'Wadi - Amravati Road NH-53 Nallah Overpass',
    marathiName: 'वाडी - अमरावती महामार्ग नाला ओव्हरपास',
    zone: 'Dharampeth (Zone 2 / Western Outskirts)',
    wardNo: 'Wadi Municipal Council',
    lat: 21.1485,
    lng: 78.9985,
    category: 'Industrial / Highway Corridor',
    baseRisk: 'severe',
    elevationMeters: 318,
    vulnerabilityFactor: 'Highway expansion construction narrowing original nallah cross-section',
    historicalEvent: 'West-bound vehicular traffic diverted via MIDC Hingna due to flood sheet on road',
    drainageCapacity: '56%',
    nearestNDRFPost: 'Wadi Fire Station (1.2 km)',
    emergencyHelpline: '0712-2567012',
    nodalContact: 'Shri Rajesh Sharma (EE Dharampeth)',
    evacuationShelter: 'Wadi Nagar Parishad Community Hall',
    populationImpactedEstimate: 13000,
    liveWaterLevelCm: 100,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-22',
    name: 'Hingna MIDC Electronic Zone Nallah Crossing',
    marathiName: 'हिंगणा एमआयडीसी इलेक्ट्रॉनिक झोन नाला',
    zone: 'Laxmi Nagar (Zone 1 / Hingna)',
    wardNo: 'MIDC Zone 1',
    lat: 21.1125,
    lng: 79.0125,
    category: 'Industrial / Highway Corridor',
    baseRisk: 'moderate',
    elevationMeters: 310,
    vulnerabilityFactor: 'Industrial runoff mixing with Vena river feeder creek during torrential rain',
    historicalEvent: 'Transformer yard inundated shutting down power to 45 manufacturing plants',
    drainageCapacity: '72%',
    nearestNDRFPost: 'MIDC Hingna Fire Station (0.8 km)',
    emergencyHelpline: '0712-2567011',
    nodalContact: 'Shri Aniket Rane (EE Laxmi Nagar)',
    evacuationShelter: 'MIDC Officers Club & YCCE Campus Auditoriums',
    populationImpactedEstimate: 8900,
    liveWaterLevelCm: 48,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-23',
    name: 'Pratap Nagar Ring Road Square & Telecom Nagar Lows',
    marathiName: 'प्रताप नगर रिंग रोड चौक व टेलिकॉम नगर',
    zone: 'Laxmi Nagar (Zone 1)',
    wardNo: 'Ward 38',
    lat: 21.1185,
    lng: 79.0545,
    category: 'Low-lying Residential',
    baseRisk: 'moderate',
    elevationMeters: 307,
    vulnerabilityFactor: 'Surface water converging from Khamla hills into Telecom nagar nallah',
    historicalEvent: 'Basement libraries and computer institutes waterlogged',
    drainageCapacity: '74%',
    nearestNDRFPost: 'VNIT Disaster Post (1.6 km)',
    emergencyHelpline: '0712-2567011',
    nodalContact: 'Shri Aniket Rane (EE Laxmi Nagar)',
    evacuationShelter: 'Pratap Nagar Samaj Bhavan',
    populationImpactedEstimate: 6800,
    liveWaterLevelCm: 42,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-24',
    name: 'Khamla Old Sindhi Colony & Sabzi Mandi Basin',
    marathiName: 'खामला जुनी सिंधी कॉलनी व भाजी बाजार',
    zone: 'Laxmi Nagar (Zone 1)',
    wardNo: 'Ward 37',
    lat: 21.1142,
    lng: 79.0621,
    category: 'Commercial / Market Drain Choke',
    baseRisk: 'severe',
    elevationMeters: 304,
    vulnerabilityFactor: 'Encroached open nullah running directly through market stalls',
    historicalEvent: 'Severe waterlogging up to 3 feet with contaminated tap water reports',
    drainageCapacity: '52%',
    nearestNDRFPost: 'Sonegaon Disaster Base (1.5 km)',
    emergencyHelpline: '0712-2567011',
    nodalContact: 'Shri Aniket Rane (EE Laxmi Nagar)',
    evacuationShelter: 'Khamla Sindhi Panchayat Bhavan',
    populationImpactedEstimate: 10500,
    liveWaterLevelCm: 92,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-25',
    name: 'Wardha Road - Chhatrapati Square Flyover Under-deck',
    marathiName: 'वर्धा रोड - छत्रपती चौक उड्डाणपूल तळभाग',
    zone: 'Laxmi Nagar (Zone 1)',
    wardNo: 'Ward 35',
    lat: 21.1158,
    lng: 79.0712,
    category: 'Bridge / Flyover Approach',
    baseRisk: 'moderate',
    elevationMeters: 302,
    vulnerabilityFactor: 'Heavy intersection traffic with storm grates covered by asphalt overlays',
    historicalEvent: 'Airport connector route paralyzed for 3 hours during monsoon storm',
    drainageCapacity: '68%',
    nearestNDRFPost: 'Sonegaon Rescue Station (1.8 km)',
    emergencyHelpline: '0712-2567011',
    nodalContact: 'Shri Aniket Rane (EE Laxmi Nagar)',
    evacuationShelter: 'Dr. Ambedkar College Campus Hall',
    populationImpactedEstimate: 21000,
    liveWaterLevelCm: 52,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-26',
    name: 'Ajni Railway Colony & Chunabhatti Slum Stream',
    marathiName: 'अजनी रेल्वे कॉलनी व चुनाभट्टी झोपडपट्टी',
    zone: 'Dhantoli (Zone 4)',
    wardNo: 'Ward 34',
    lat: 21.1275,
    lng: 79.0855,
    category: 'Slum / Riverbank Settlement',
    baseRisk: 'severe',
    elevationMeters: 299,
    vulnerabilityFactor: 'Informal tin-shed settlements on railway drain slope susceptible to mudslides',
    historicalEvent: 'Wall collapse and emergency evacuation of 80 slum households in July 2023',
    drainageCapacity: '45%',
    nearestNDRFPost: 'Ganeshpeth Fire HQ (2.1 km)',
    emergencyHelpline: '0712-2567014',
    nodalContact: 'Smt. Kavita Patil (EE Dhantoli)',
    evacuationShelter: 'Railway Institute Ajni & Community School',
    populationImpactedEstimate: 7200,
    liveWaterLevelCm: 118,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-27',
    name: 'Rambagh Slum & Medical College Nallah Outlet',
    marathiName: 'रामबाग झोपडपट्टी व मेडिकल कॉलेज नाला आउटलेट',
    zone: 'Hanuman Nagar (Zone 3)',
    wardNo: 'Ward 31',
    lat: 21.1345,
    lng: 79.0982,
    category: 'Slum / Riverbank Settlement',
    baseRisk: 'severe',
    elevationMeters: 298,
    vulnerabilityFactor: 'Biomedical runoff mixing with untreated sewage during torrential overflow',
    historicalEvent: 'Govt Medical College lower OPD gates blocked by 2 feet stormwater',
    drainageCapacity: '55%',
    nearestNDRFPost: 'Sakkardara Rescue Base (1.5 km)',
    emergencyHelpline: '0712-2567013',
    nodalContact: 'Shri Suresh Khare (EE Hanuman Nagar)',
    evacuationShelter: 'GMC Nagpur Auditorium & Rambagh ZP School',
    populationImpactedEstimate: 9600,
    liveWaterLevelCm: 95,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-28',
    name: 'Untkhana Road - Medical Square Water Vortex',
    marathiName: 'उंटखाना रोड - मेडिकल चौक पाणी प्रवाह जंक्शन',
    zone: 'Hanuman Nagar (Zone 3)',
    wardNo: 'Ward 32',
    lat: 21.1312,
    lng: 79.0925,
    category: 'Low-lying Residential',
    baseRisk: 'moderate',
    elevationMeters: 301,
    vulnerabilityFactor: 'Four-way gradient directing water toward hospital ambulances entrance',
    historicalEvent: 'Ambulance movements delayed due to deep water puddles',
    drainageCapacity: '70%',
    nearestNDRFPost: 'Ganeshpeth Central Station (1.2 km)',
    emergencyHelpline: '0712-2567013',
    nodalContact: 'Shri Suresh Khare (EE Hanuman Nagar)',
    evacuationShelter: 'Ayurvedic College Hall',
    populationImpactedEstimate: 14000,
    liveWaterLevelCm: 46,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-29',
    name: 'Reshimbagh Ground Perimeter & CPWD Quarters',
    marathiName: 'रेशीमबाग मैदान परिसर व सीपीडब्ल्यूडी क्वार्टर्स',
    zone: 'Nehru Nagar (Zone 5)',
    wardNo: 'Ward 27',
    lat: 21.1278,
    lng: 79.1092,
    category: 'Low-lying Residential',
    baseRisk: 'moderate',
    elevationMeters: 300,
    vulnerabilityFactor: 'Large open ground acting as a water catchment that overflows onto adjacent roads',
    historicalEvent: 'Ground transformed into a muddy lake halting sports and cultural activities',
    drainageCapacity: '65%',
    nearestNDRFPost: 'Sakkardara Station (1.0 km)',
    emergencyHelpline: '0712-2567015',
    nodalContact: 'Shri Anand Mankar (EE Nehru Nagar)',
    evacuationShelter: 'Suresh Bhat Sabhagruh (Upper Foyer)',
    populationImpactedEstimate: 8500,
    liveWaterLevelCm: 38,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-30',
    name: 'Itwari - Sarafa Bazaar & Marwari Chowk Underground Vaults',
    marathiName: 'इतवारी - सराफा बाजार व मारवाडी चौक',
    zone: 'Gandhibagh (Zone 6)',
    wardNo: 'Ward 22',
    lat: 21.1525,
    lng: 79.1121,
    category: 'Commercial / Market Drain Choke',
    baseRisk: 'severe',
    elevationMeters: 300,
    vulnerabilityFactor: 'Very narrow commercial alleys with heavy cloth and packing material choking drains',
    historicalEvent: 'Millions worth wholesale cloth goods soaked in basement shops',
    drainageCapacity: '50%',
    nearestNDRFPost: 'Gandhibagh Station (0.6 km)',
    emergencyHelpline: '0712-2567016',
    nodalContact: 'Shri Sanjay Ingle (EE Gandhibagh)',
    evacuationShelter: 'Itwari Wholesale Merchant Association Bhavan',
    populationImpactedEstimate: 19500,
    liveWaterLevelCm: 88,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-31',
    name: 'Satranjipura Central & Shanti Nagar Nallah Bed',
    marathiName: 'सतरंजीपुरा मध्यवर्ती व शांती नगर नाला',
    zone: 'Satranjipura (Zone 7)',
    wardNo: 'Ward 23',
    lat: 21.1612,
    lng: 79.1215,
    category: 'Low-lying Residential',
    baseRisk: 'severe',
    elevationMeters: 297,
    vulnerabilityFactor: 'Pili river backflow during continuous rain flooding residential colonies',
    historicalEvent: '1200 residents shifted to relief shelters in primary schools',
    drainageCapacity: '54%',
    nearestNDRFPost: 'Kalamna Fire Station (1.9 km)',
    emergencyHelpline: '0712-2567017',
    nodalContact: 'Shri Dilip Gedam (EE Satranjipura)',
    evacuationShelter: 'Shanti Nagar Municipal High School',
    populationImpactedEstimate: 11500,
    liveWaterLevelCm: 102,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-32',
    name: 'Bagadganj Timber Market & Garoba Maidan Stream',
    marathiName: 'बागडगंज लाकूड बाजार व गरोबा मैदान',
    zone: 'Lakadganj (Zone 8)',
    wardNo: 'Ward 25',
    lat: 21.1445,
    lng: 79.1285,
    category: 'Commercial / Market Drain Choke',
    baseRisk: 'moderate',
    elevationMeters: 299,
    vulnerabilityFactor: 'Wood shavings and sawdust deposits blocking roadside brick masonry channels',
    historicalEvent: 'Floating timber logs creating severe hazard on main arterial road',
    drainageCapacity: '60%',
    nearestNDRFPost: 'Lakadganj Fire Outpost (0.8 km)',
    emergencyHelpline: '0712-2567018',
    nodalContact: 'Smt. Priya Channe (EE Lakadganj)',
    evacuationShelter: 'Garoba Maidan Community Hall',
    populationImpactedEstimate: 8700,
    liveWaterLevelCm: 48,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-33',
    name: 'Mini Mata Nagar - Pili River Confluence Slums',
    marathiName: 'मिनी माता नगर - पिळी नदी संगम झोपडपट्टी',
    zone: 'Lakadganj (Zone 8)',
    wardNo: 'Ward 26',
    lat: 21.1558,
    lng: 79.1512,
    category: 'Slum / Riverbank Settlement',
    baseRisk: 'severe',
    elevationMeters: 294,
    vulnerabilityFactor: 'Houses built directly on the mud floodplains without flood protection bunds',
    historicalEvent: 'Rescue boats deployed to evacuate elderly and children in 2023 deluge',
    drainageCapacity: '42%',
    nearestNDRFPost: 'Kalamna Disaster Post (1.5 km)',
    emergencyHelpline: '0712-2567018',
    nodalContact: 'Smt. Priya Channe (EE Lakadganj)',
    evacuationShelter: 'Surya Nagar ZP School',
    populationImpactedEstimate: 6800,
    liveWaterLevelCm: 120,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-34',
    name: 'Nari Road & Kapil Nagar Railway Crossing Dip',
    marathiName: 'नारी रोड व कपिल नगर रेल्वे क्रॉसिंग',
    zone: 'Ashi Nagar (Zone 9)',
    wardNo: 'Ward 09',
    lat: 21.1872,
    lng: 79.1125,
    category: 'Low-lying Residential',
    baseRisk: 'moderate',
    elevationMeters: 299,
    vulnerabilityFactor: 'Stormwater from Uppalwadi railway siding trapped behind track ballast',
    historicalEvent: 'Level crossing submerged preventing school vans and city buses from passing',
    drainageCapacity: '62%',
    nearestNDRFPost: 'Sugat Nagar Rescue Post (1.8 km)',
    emergencyHelpline: '0712-2567019',
    nodalContact: 'Smt. Vandana Meshram (EE Ashi Nagar)',
    evacuationShelter: 'Kapil Nagar Buddha Vihar Hall',
    populationImpactedEstimate: 7600,
    liveWaterLevelCm: 44,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-35',
    name: 'Zingabai Takli - Godhani Road Nallah Breach Point',
    marathiName: 'झिंगाबाई टाकळी - गोधनी रोड नाला प्रवाह',
    zone: 'Mangalwari (Zone 10)',
    wardNo: 'Ward 02',
    lat: 21.1985,
    lng: 79.0621,
    category: 'Low-lying Residential',
    baseRisk: 'moderate',
    elevationMeters: 309,
    vulnerabilityFactor: 'Rapid hilly slope runoff causing flash torrents down residential streets',
    historicalEvent: 'Boundary walls collapsed under velocity of water coming from Godhani plateau',
    drainageCapacity: '66%',
    nearestNDRFPost: 'Mankapur Fire Post (2.4 km)',
    emergencyHelpline: '0712-2567020',
    nodalContact: 'Shri Nitin Bhende (EE Mangalwari)',
    evacuationShelter: 'Zingabai Takli High School',
    populationImpactedEstimate: 9200,
    liveWaterLevelCm: 50,
    cctvStreamAvailable: true,
  },

  // 36-50: Northern, Western & South-Western Extended Hotspots
  {
    id: 'HOT-36',
    name: 'Gorewada Lake Spillway Channel & Borgaon Nallah',
    marathiName: 'गोरेवाडा तलाव सांडवा नाला व बोरगाव',
    zone: 'Mangalwari (Zone 10)',
    wardNo: 'Ward 04',
    lat: 21.1812,
    lng: 79.0355,
    category: 'Reservoir / Canal Discharge',
    baseRisk: 'severe',
    elevationMeters: 314,
    vulnerabilityFactor: 'Release from Gorewada reservoir overflowing downstream agricultural/residential plots',
    historicalEvent: 'Controlled spillway opening warning issued to 4 downstream villages',
    drainageCapacity: '75%',
    nearestNDRFPost: 'Gorewada Forest Patrol Base (1.0 km)',
    emergencyHelpline: '0712-2567020',
    nodalContact: 'Shri Nitin Bhende (EE Mangalwari)',
    evacuationShelter: 'Borgaon Community Center',
    populationImpactedEstimate: 5100,
    liveWaterLevelCm: 75,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-37',
    name: 'Seminary Hills Foothill Channel & TV Tower Slope',
    marathiName: 'सेमिनरी हिल्स पायथा नाला व टीव्ही टॉवर उतार',
    zone: 'Dharampeth (Zone 2)',
    wardNo: 'Ward 11',
    lat: 21.1645,
    lng: 79.0521,
    category: 'Low-lying Residential',
    baseRisk: 'normal',
    elevationMeters: 325,
    vulnerabilityFactor: 'High velocity mud slurry runoff down Seminary Hills into CPWD colony',
    historicalEvent: 'Road blocked by soil deposits and fallen trees',
    drainageCapacity: '80%',
    nearestNDRFPost: 'Civil Lines SDRF Camp (1.5 km)',
    emergencyHelpline: '0712-2567012',
    nodalContact: 'Shri Rajesh Sharma (EE Dharampeth)',
    evacuationShelter: 'Air Force School Seminar Hall',
    populationImpactedEstimate: 3400,
    liveWaterLevelCm: 25,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-38',
    name: 'Futala Lake Outfall Weir & Telankhedi Hanuman Temple Road',
    marathiName: 'फुटाळा तलाव आउटफॉल व तेलंगखेडी मारोती मंदिर रस्ता',
    zone: 'Dharampeth (Zone 2)',
    wardNo: 'Ward 13',
    lat: 21.1542,
    lng: 79.0415,
    category: 'Reservoir / Canal Discharge',
    baseRisk: 'moderate',
    elevationMeters: 310,
    vulnerabilityFactor: 'Tourist promenade level vulnerable to lake surge during high winds and rainfall',
    historicalEvent: 'Food plaza kiosks submerged and promenade walkway barricaded',
    drainageCapacity: '78%',
    nearestNDRFPost: 'VNIT Disaster Sub-Station (2.0 km)',
    emergencyHelpline: '0712-2567012',
    nodalContact: 'Shri Rajesh Sharma (EE Dharampeth)',
    evacuationShelter: 'College of Agriculture Telankhedi Campus',
    populationImpactedEstimate: 6200,
    liveWaterLevelCm: 45,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-39',
    name: 'Civil Lines - High Court Road & VCA Stadium Dip',
    marathiName: 'सिव्हिल लाईन्स - हायकोर्ट रोड व व्हीसीए मैदान',
    zone: 'Dharampeth (Zone 2)',
    wardNo: 'Ward 10',
    lat: 21.1585,
    lng: 79.0715,
    category: 'Low-lying Residential',
    baseRisk: 'normal',
    elevationMeters: 315,
    vulnerabilityFactor: 'Wide avenue trees shed leaves that clog storm curb inlets',
    historicalEvent: 'Minor puddling clearing within 30 minutes of rain stoppage',
    drainageCapacity: '88%',
    nearestNDRFPost: 'Civil Lines Station (0.5 km)',
    emergencyHelpline: '0712-2567012',
    nodalContact: 'Shri Rajesh Sharma (EE Dharampeth)',
    evacuationShelter: 'Vidhan Bhavan Administrative Annex',
    populationImpactedEstimate: 2800,
    liveWaterLevelCm: 15,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-40',
    name: 'Gokulpeth Market & West High Court (WHC) Road Junction',
    marathiName: 'गोकुळपेठ बाजार व वेस्ट हायकोर्ट रोड जंक्शन',
    zone: 'Dharampeth (Zone 2)',
    wardNo: 'Ward 15',
    lat: 21.1398,
    lng: 79.0552,
    category: 'Commercial / Market Drain Choke',
    baseRisk: 'moderate',
    elevationMeters: 309,
    vulnerabilityFactor: 'Intense shopping traffic with temporary roadside stalls impeding drainage flow',
    historicalEvent: 'Ground floor sweet shops and grocery stores affected',
    drainageCapacity: '72%',
    nearestNDRFPost: 'VNIT Disaster Post (1.4 km)',
    emergencyHelpline: '0712-2567012',
    nodalContact: 'Shri Rajesh Sharma (EE Dharampeth)',
    evacuationShelter: 'Gokulpeth Municipal Primary School',
    populationImpactedEstimate: 11000,
    liveWaterLevelCm: 35,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-41',
    name: 'Laxmi Nagar Square & Water Tank Low Depression',
    marathiName: 'लक्ष्मीनगर चौक व पाण्याची टाकी परिसर',
    zone: 'Laxmi Nagar (Zone 1)',
    wardNo: 'Ward 39',
    lat: 21.1245,
    lng: 79.0665,
    category: 'Low-lying Residential',
    baseRisk: 'normal',
    elevationMeters: 308,
    vulnerabilityFactor: 'Localized depression near garden square collecting local street flow',
    historicalEvent: 'Water logged up to 1.5 ft for 45 mins before gravity drainage',
    drainageCapacity: '82%',
    nearestNDRFPost: 'VNIT Disaster Sub-Station (0.9 km)',
    emergencyHelpline: '0712-2567011',
    nodalContact: 'Shri Aniket Rane (EE Laxmi Nagar)',
    evacuationShelter: 'Laxmi Nagar Scientific Society Hall',
    populationImpactedEstimate: 4500,
    liveWaterLevelCm: 20,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-42',
    name: 'Sonegaon Lake Catchment & Sahakar Nagar Stream',
    marathiName: 'सोनेगाव तलाव पाणलोट क्षेत्र व सहकार नगर',
    zone: 'Laxmi Nagar (Zone 1)',
    wardNo: 'Ward 40',
    lat: 21.1012,
    lng: 79.0585,
    category: 'Reservoir / Canal Discharge',
    baseRisk: 'moderate',
    elevationMeters: 303,
    vulnerabilityFactor: 'Lake siltation reducing holding capacity during cloudburst events',
    historicalEvent: 'Lake water overtopped stone bund entering Sahakar nagar colony roads',
    drainageCapacity: '70%',
    nearestNDRFPost: 'Sonegaon Disaster Station (0.5 km)',
    emergencyHelpline: '0712-2567011',
    nodalContact: 'Shri Aniket Rane (EE Laxmi Nagar)',
    evacuationShelter: 'Sonegaon Sanskritik Bhavan',
    populationImpactedEstimate: 6200,
    liveWaterLevelCm: 48,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-43',
    name: 'Nagpur Airport Runway Western Perimeter Drain',
    marathiName: 'नागपूर विमानतळ रनवे पश्चिम सीमा नाला',
    zone: 'Laxmi Nagar (Zone 1)',
    wardNo: 'MIHAN / Airport Boundary',
    lat: 21.0915,
    lng: 79.0512,
    category: 'Industrial / Highway Corridor',
    baseRisk: 'moderate',
    elevationMeters: 312,
    vulnerabilityFactor: 'Critical perimeter stormwater culvert to maintain airport operational readiness',
    historicalEvent: 'Precautionary high-capacity diesel dewatering pump deployment in 2023',
    drainageCapacity: '85%',
    nearestNDRFPost: 'AAI Airport Fire & Rescue Unit (0.2 km)',
    emergencyHelpline: '0712-2567011',
    nodalContact: 'Shri Aniket Rane (EE Laxmi Nagar)',
    evacuationShelter: 'MIHAN Administration Building Foyer',
    populationImpactedEstimate: 3000,
    liveWaterLevelCm: 30,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-44',
    name: 'MIHAN SEZ - TCS / Infosys Junction Culvert',
    marathiName: 'मिहान सेझ - टीसीएस / इन्फोसिस जंक्शन कल्व्हर्ट',
    zone: 'Rural / MIHAN Special Zone',
    wardNo: 'MIHAN SEZ 2',
    lat: 21.0545,
    lng: 79.0385,
    category: 'Industrial / Highway Corridor',
    baseRisk: 'normal',
    elevationMeters: 316,
    vulnerabilityFactor: 'Wide multi-lane arterial road collecting extensive paved runoff',
    historicalEvent: 'Minor curb ponding; well-engineered underground RCC drains operational',
    drainageCapacity: '90%',
    nearestNDRFPost: 'MIHAN Central Station (1.0 km)',
    emergencyHelpline: '0712-2567030',
    nodalContact: 'Shri Milind Deshmukh (EE PWD Rural)',
    evacuationShelter: 'MIHAN Multi-Modal Transport Terminal',
    populationImpactedEstimate: 4200,
    liveWaterLevelCm: 12,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-45',
    name: 'Butibori MIDC - Krishna Nallah Overflow Point',
    marathiName: 'बुटीबोरी एमआयडीसी - कृष्णा नाला प्रवाह',
    zone: 'Rural / Butibori Industrial Zone',
    wardNo: 'Butibori Phase 1',
    lat: 20.9255,
    lng: 78.9882,
    category: 'Industrial / Highway Corridor',
    baseRisk: 'severe',
    elevationMeters: 290,
    vulnerabilityFactor: 'Massive textile and engineering industrial catchment during continuous rain',
    historicalEvent: 'Internal MIDC road submerged cutting off worker shifts for 12 hours',
    drainageCapacity: '60%',
    nearestNDRFPost: 'Butibori Fire Station (1.1 km)',
    emergencyHelpline: '0712-2567030',
    nodalContact: 'Shri Milind Deshmukh (EE PWD Rural)',
    evacuationShelter: 'BMA Manufacturers Association Hall',
    populationImpactedEstimate: 14000,
    liveWaterLevelCm: 95,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-46',
    name: 'Dighori Ring Road Nallah Confluence & Telephone Nagar',
    marathiName: 'दिघोरी रिंग रोड नाला व टेलिफोन नगर',
    zone: 'Nehru Nagar (Zone 5)',
    wardNo: 'Ward 29',
    lat: 21.1095,
    lng: 79.1385,
    category: 'River / Waterbody Overflow',
    baseRisk: 'severe',
    elevationMeters: 295,
    vulnerabilityFactor: 'Pora River branch converging at right angle to national highway box drain',
    historicalEvent: 'Backwater flooded 500+ small residences along Dighori toll plaza corridor',
    drainageCapacity: '50%',
    nearestNDRFPost: 'Sakkardara Rescue Base (3.0 km)',
    emergencyHelpline: '0712-2567015',
    nodalContact: 'Shri Anand Mankar (EE Nehru Nagar)',
    evacuationShelter: 'Dighori ZP School & Samaj Bhavan',
    populationImpactedEstimate: 11200,
    liveWaterLevelCm: 112,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-47',
    name: 'Wathoda Ring Road & Symbiosis Campus Approach',
    marathiName: 'वाठोडा रिंग रोड व सिम्बायोसिस कॅम्पस रस्ता',
    zone: 'Nehru Nagar (Zone 5)',
    wardNo: 'Ward 28',
    lat: 21.1292,
    lng: 79.1492,
    category: 'Low-lying Residential',
    baseRisk: 'moderate',
    elevationMeters: 296,
    vulnerabilityFactor: 'Newly constructed concrete highways lacking integrated side stormwater canals',
    historicalEvent: 'Students and vehicles stranded in 2 ft water sheet on Ring Road',
    drainageCapacity: '65%',
    nearestNDRFPost: 'Kalamna Fire Station (3.2 km)',
    emergencyHelpline: '0712-2567015',
    nodalContact: 'Shri Anand Mankar (EE Nehru Nagar)',
    evacuationShelter: 'Symbiosis Campus Main Auditorium',
    populationImpactedEstimate: 6500,
    liveWaterLevelCm: 50,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-48',
    name: 'Kharbi Chowk & Tajbagh Low Drainage Route',
    marathiName: 'खरबी चौक व ताजबाग सखल भाग',
    zone: 'Nehru Nagar (Zone 5)',
    wardNo: 'Ward 27',
    lat: 21.1185,
    lng: 79.1315,
    category: 'Slum / Riverbank Settlement',
    baseRisk: 'severe',
    elevationMeters: 295,
    vulnerabilityFactor: 'Pilgrim congregation area with low soil absorption and heavy clay base',
    historicalEvent: 'Devotees dharamsalas inundated requiring emergency pumping',
    drainageCapacity: '52%',
    nearestNDRFPost: 'Sakkardara Station (2.2 km)',
    emergencyHelpline: '0712-2567015',
    nodalContact: 'Shri Anand Mankar (EE Nehru Nagar)',
    evacuationShelter: 'Tajbagh Trust Community Hall',
    populationImpactedEstimate: 13500,
    liveWaterLevelCm: 105,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-49',
    name: 'Pachpaoli Railway Overbridge Approach & Golibar Chowk',
    marathiName: 'पाचपावली उड्डाणपूल व गोळीबार चौक',
    zone: 'Satranjipura (Zone 7)',
    wardNo: 'Ward 21',
    lat: 21.1625,
    lng: 79.1025,
    category: 'Bridge / Flyover Approach',
    baseRisk: 'severe',
    elevationMeters: 300,
    vulnerabilityFactor: 'Funnel effect of bridge ramp directing water into historical densely packed slums',
    historicalEvent: 'Ground floor power meters submerged forcing emergency power feeder trip',
    drainageCapacity: '54%',
    nearestNDRFPost: 'Gandhibagh Station (1.2 km)',
    emergencyHelpline: '0712-2567017',
    nodalContact: 'Shri Dilip Gedam (EE Satranjipura)',
    evacuationShelter: 'Pachpaoli Maternity Hospital Annex',
    populationImpactedEstimate: 12500,
    liveWaterLevelCm: 90,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-50',
    name: 'Kamal Chowk & Lashkaribagh Handloom Cluster',
    marathiName: 'कमाल चौक व लष्करीबाग हातमाग वस्ती',
    zone: 'Satranjipura (Zone 7)',
    wardNo: 'Ward 22',
    lat: 21.1695,
    lng: 79.0982,
    category: 'Low-lying Residential',
    baseRisk: 'moderate',
    elevationMeters: 301,
    vulnerabilityFactor: 'Traditional weaver pit looms located below street grade prone to flooding',
    historicalEvent: 'Weaving looms and raw yarn severely damaged in July 2023',
    drainageCapacity: '62%',
    nearestNDRFPost: 'Sugat Nagar Rescue Post (1.6 km)',
    emergencyHelpline: '0712-2567017',
    nodalContact: 'Shri Dilip Gedam (EE Satranjipura)',
    evacuationShelter: 'Kamal Talkies Hall & Weavers Society Bhavan',
    populationImpactedEstimate: 8200,
    liveWaterLevelCm: 55,
    cctvStreamAvailable: false,
  },

  // 51-65: Eastern, Northern & Metropolitan Extended Hotspots
  {
    id: 'HOT-51',
    name: 'Yashodhara Nagar - Pili River Embankment Breach Zone',
    marathiName: 'यशोधरा नगर - पिळी नदी तटबंध क्षेत्र',
    zone: 'Ashi Nagar (Zone 9)',
    wardNo: 'Ward 06',
    lat: 21.1912,
    lng: 79.1315,
    category: 'River / Waterbody Overflow',
    baseRisk: 'severe',
    elevationMeters: 295,
    vulnerabilityFactor: 'Absence of concrete retaining walls along winding river bends',
    historicalEvent: '300 tin-roofed huts submerged to lintel height; NDRF rescued 45 citizens',
    drainageCapacity: '40%',
    nearestNDRFPost: 'Sugat Nagar Rescue Station (2.0 km)',
    emergencyHelpline: '0712-2567019',
    nodalContact: 'Smt. Vandana Meshram (EE Ashi Nagar)',
    evacuationShelter: 'Yashodhara Nagar Urdu School',
    populationImpactedEstimate: 9800,
    liveWaterLevelCm: 140,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-52',
    name: 'Teka Naka - Kamptee Road Metro Pier Basin',
    marathiName: 'टेका नाका - कामठी रोड मेट्रो पिलर तळभाग',
    zone: 'Ashi Nagar (Zone 9)',
    wardNo: 'Ward 08',
    lat: 21.1815,
    lng: 79.1195,
    category: 'Commercial / Market Drain Choke',
    baseRisk: 'moderate',
    elevationMeters: 298,
    vulnerabilityFactor: 'Construction debris and uncleaned roadside culverts',
    historicalEvent: 'Traffic stalled for 4 hours; small transport operators suffered water damage',
    drainageCapacity: '64%',
    nearestNDRFPost: 'Automotive Square Station (1.5 km)',
    emergencyHelpline: '0712-2567019',
    nodalContact: 'Smt. Vandana Meshram (EE Ashi Nagar)',
    evacuationShelter: 'Teka Naka Community Clinic Hall',
    populationImpactedEstimate: 7800,
    liveWaterLevelCm: 48,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-53',
    name: 'Nara Ghat & Nara Road Rural Tributary Outfall',
    marathiName: 'नारा घाट व नारा रोड ग्रामीण नाला',
    zone: 'Mangalwari (Zone 10)',
    wardNo: 'Ward 05',
    lat: 21.2095,
    lng: 79.0885,
    category: 'River / Waterbody Overflow',
    baseRisk: 'moderate',
    elevationMeters: 302,
    vulnerabilityFactor: 'Agricultural runoff carrying crop stalks that block road culverts',
    historicalEvent: 'Bridge submerged cutting off direct link between Nara and Jaripatka',
    drainageCapacity: '68%',
    nearestNDRFPost: 'Mankapur Fire Outpost (2.8 km)',
    emergencyHelpline: '0712-2567020',
    nodalContact: 'Shri Nitin Bhende (EE Mangalwari)',
    evacuationShelter: 'Nara Gram Panchayat Hall',
    populationImpactedEstimate: 5400,
    liveWaterLevelCm: 52,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-54',
    name: 'Godhani Railway Station Sub-surface Lows',
    marathiName: 'गोधनी रेल्वे स्थानक तळभाग',
    zone: 'Rural / Western Suburban',
    wardNo: 'Godhani Rly Sector',
    lat: 21.2155,
    lng: 79.0492,
    category: 'Underpass Waterlogging',
    baseRisk: 'severe',
    elevationMeters: 306,
    vulnerabilityFactor: 'Railway subway lacking automated high-volume drainage pump array',
    historicalEvent: 'Passenger subway inundated under 5 ft water halting suburban transit',
    drainageCapacity: '48%',
    nearestNDRFPost: 'Mankapur Fire Post (3.5 km)',
    emergencyHelpline: '0712-2567030',
    nodalContact: 'Shri Milind Deshmukh (EE PWD Rural)',
    evacuationShelter: 'Godhani Railway Waiting Hall & ZP School',
    populationImpactedEstimate: 6100,
    liveWaterLevelCm: 115,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-55',
    name: 'Koradi Road - Modern School Square & Mankapur Dip',
    marathiName: 'कोराडी रोड - मॉडर्न स्कूल चौक व मानकापूर',
    zone: 'Mangalwari (Zone 10)',
    wardNo: 'Ward 01',
    lat: 21.1945,
    lng: 79.0812,
    category: 'Bridge / Flyover Approach',
    baseRisk: 'normal',
    elevationMeters: 305,
    vulnerabilityFactor: 'Four-lane highway median drainage overflows during severe rain spells',
    historicalEvent: 'School buses delayed; traffic police deployed for manual diversion',
    drainageCapacity: '80%',
    nearestNDRFPost: 'Mankapur Post (0.8 km)',
    emergencyHelpline: '0712-2567020',
    nodalContact: 'Shri Nitin Bhende (EE Mangalwari)',
    evacuationShelter: 'Modern School Auditorium',
    populationImpactedEstimate: 4500,
    liveWaterLevelCm: 22,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-56',
    name: 'Mahadula - Kolar River Flood Zone & Power Colony',
    marathiName: 'महादुला - कोलार नदी पूर क्षेत्र व पॉवर कॉलनी',
    zone: 'Rural / Northern Metropolitan',
    wardNo: 'Mahadula Nagar Panchayat',
    lat: 21.2715,
    lng: 79.0815,
    category: 'River / Waterbody Overflow',
    baseRisk: 'severe',
    elevationMeters: 298,
    vulnerabilityFactor: 'Flash floods from Kolar river during heavy catchment rainfall in Satpura hills',
    historicalEvent: 'Mahadula bridge overtopped with red alert issued to 5000 riverbank residents',
    drainageCapacity: '55%',
    nearestNDRFPost: 'Koradi SDRF Outpost (2.2 km)',
    emergencyHelpline: '0712-2567030',
    nodalContact: 'Shri Milind Deshmukh (EE PWD Rural)',
    evacuationShelter: 'Mahadula Municipal Primary School',
    populationImpactedEstimate: 8700,
    liveWaterLevelCm: 125,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-57',
    name: 'Kamptee Old Town - Kanhan River Bank Slums',
    marathiName: 'कामठी जुने शहर - कन्हान नदी काठ',
    zone: 'Rural / Eastern Metropolitan (Kamptee)',
    wardNo: 'Kamptee Ward 12',
    lat: 21.2285,
    lng: 79.2012,
    category: 'River / Waterbody Overflow',
    baseRisk: 'severe',
    elevationMeters: 292,
    vulnerabilityFactor: 'High river swell of Kanhan river forcing backwater into storm outfalls',
    historicalEvent: 'Military rescue boats mobilized from Kamptee Cantonment in 2022',
    drainageCapacity: '45%',
    nearestNDRFPost: 'Kamptee Military Cantonment Quick Response Unit (1.0 km)',
    emergencyHelpline: '0712-2567030',
    nodalContact: 'Shri Milind Deshmukh (EE PWD Rural)',
    evacuationShelter: 'Dragon Palace Temple Pilgrimage Hall & Kamptee Cantonment School',
    populationImpactedEstimate: 16000,
    liveWaterLevelCm: 145,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-58',
    name: 'Dragon Palace Temple Low Plains & Gauri Nagar',
    marathiName: 'ड्रॅगन पॅलेस टेम्पल परिसर व गौरी नगर',
    zone: 'Rural / Kamptee',
    wardNo: 'Kamptee Ward 08',
    lat: 21.2195,
    lng: 79.1895,
    category: 'Low-lying Residential',
    baseRisk: 'moderate',
    elevationMeters: 295,
    vulnerabilityFactor: 'Low-lying clay basin retaining surface moisture for prolonged duration',
    historicalEvent: 'Temple complex lawns flooded; pilgrim movements restricted',
    drainageCapacity: '68%',
    nearestNDRFPost: 'Kamptee Fire Station (1.8 km)',
    emergencyHelpline: '0712-2567030',
    nodalContact: 'Shri Milind Deshmukh (EE PWD Rural)',
    evacuationShelter: 'Dragon Palace VIP Guest Annex',
    populationImpactedEstimate: 7200,
    liveWaterLevelCm: 45,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-59',
    name: 'Kalamna Old Village & Railway Culvert Choke',
    marathiName: 'कळमना जुने गाव व रेल्वे कल्व्हर्ट',
    zone: 'Satranjipura (Zone 7)',
    wardNo: 'Ward 24',
    lat: 21.1685,
    lng: 79.1355,
    category: 'Underpass Waterlogging',
    baseRisk: 'severe',
    elevationMeters: 297,
    vulnerabilityFactor: 'Railway embankment blocks natural flow toward east, creating a temporary dam',
    historicalEvent: 'Houses in old village inundated up to 4 ft; relief ration packets distributed',
    drainageCapacity: '46%',
    nearestNDRFPost: 'Kalamna Market Station (1.0 km)',
    emergencyHelpline: '0712-2567017',
    nodalContact: 'Shri Dilip Gedam (EE Satranjipura)',
    evacuationShelter: 'Kalamna Samaj Bhavan',
    populationImpactedEstimate: 8300,
    liveWaterLevelCm: 110,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-60',
    name: 'Chikhali Layout & Bharatwada Low-land Nallah',
    marathiName: 'चिखली लेआउट व भारतवाडा नाला',
    zone: 'Lakadganj (Zone 8)',
    wardNo: 'Ward 26',
    lat: 21.1605,
    lng: 79.1625,
    category: 'Low-lying Residential',
    baseRisk: 'severe',
    elevationMeters: 293,
    vulnerabilityFactor: 'Marshy soil and low elevation (lowest in eastern Nagpur) accumulating city discharges',
    historicalEvent: '15-day water stagnation reported leading to public health alert',
    drainageCapacity: '40%',
    nearestNDRFPost: 'Kalamna Disaster Post (2.4 km)',
    emergencyHelpline: '0712-2567018',
    nodalContact: 'Smt. Priya Channe (EE Lakadganj)',
    evacuationShelter: 'Chikhali Primary Health Clinic',
    populationImpactedEstimate: 10500,
    liveWaterLevelCm: 130,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-61',
    name: 'Pardi Octroi Post & Punapur Road Dip',
    marathiName: 'पारडी जकात नाका व पुनापूर रोड',
    zone: 'Lakadganj (Zone 8)',
    wardNo: 'Ward 25',
    lat: 21.1415,
    lng: 79.1685,
    category: 'Industrial / Highway Corridor',
    baseRisk: 'moderate',
    elevationMeters: 296,
    vulnerabilityFactor: 'Heavy truck movement causes road rutting where stormwater pools deeply',
    historicalEvent: 'Commercial transport delayed; tow trucks required to pull submerged cars',
    drainageCapacity: '62%',
    nearestNDRFPost: 'Kalamna Fire Station (3.0 km)',
    emergencyHelpline: '0712-2567018',
    nodalContact: 'Smt. Priya Channe (EE Lakadganj)',
    evacuationShelter: 'Punapur Gram Panchayat Hall',
    populationImpactedEstimate: 6900,
    liveWaterLevelCm: 50,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-62',
    name: 'Bhandewadi Garbage Dumping Yard Drainage Perimeter',
    marathiName: 'भांडेवाडी डम्पिंग यार्ड परिमिती नाला',
    zone: 'Lakadganj (Zone 8)',
    wardNo: 'Ward 26',
    lat: 21.1345,
    lng: 79.1652,
    category: 'Industrial / Highway Corridor',
    baseRisk: 'severe',
    elevationMeters: 294,
    vulnerabilityFactor: 'Leachate runoff during heavy rain contaminating local open drains and groundwater',
    historicalEvent: 'High toxicity alert and emergency neutralizing powder spray along surrounding plots',
    drainageCapacity: '50%',
    nearestNDRFPost: 'Lakadganj Rescue Team (2.5 km)',
    emergencyHelpline: '0712-2567018',
    nodalContact: 'Smt. Priya Channe (EE Lakadganj)',
    evacuationShelter: 'NMC Solid Waste Management Admin Hall',
    populationImpactedEstimate: 8800,
    liveWaterLevelCm: 105,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-63',
    name: 'Sharda Chowk & Ganeshpeth Model Mill Chawl',
    marathiName: 'शारदा चौक व गणेशपेठ मॉडेल मिल चाळ',
    zone: 'Gandhibagh (Zone 6)',
    wardNo: 'Ward 20',
    lat: 21.1465,
    lng: 79.0995,
    category: 'Slum / Riverbank Settlement',
    baseRisk: 'moderate',
    elevationMeters: 301,
    vulnerabilityFactor: 'High population density in old mill worker housing with narrow lanes',
    historicalEvent: 'Water entered 200 ground-level chawl rooms with power disconnection',
    drainageCapacity: '58%',
    nearestNDRFPost: 'Ganeshpeth Central HQ (0.5 km)',
    emergencyHelpline: '0712-2567016',
    nodalContact: 'Shri Sanjay Ingle (EE Gandhibagh)',
    evacuationShelter: 'Model Mill Compound Community Center',
    populationImpactedEstimate: 7500,
    liveWaterLevelCm: 60,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-64',
    name: 'Dhantoli Mehadia Square & Canal Road Lowlands',
    marathiName: 'धंतोली मेहडिया चौक व कॅनॉल रोड',
    zone: 'Dhantoli (Zone 4)',
    wardNo: 'Ward 16',
    lat: 21.1352,
    lng: 79.0825,
    category: 'Low-lying Residential',
    baseRisk: 'moderate',
    elevationMeters: 302,
    vulnerabilityFactor: 'Dense multi-speciality hospital district prone to basement ambulance parking flooding',
    historicalEvent: 'Generator rooms in 3 major nursing homes flooded, prompting backup relocations',
    drainageCapacity: '70%',
    nearestNDRFPost: 'Ganeshpeth Station (1.4 km)',
    emergencyHelpline: '0712-2567014',
    nodalContact: 'Smt. Kavita Patil (EE Dhantoli)',
    evacuationShelter: 'IMA Hall Dhantoli',
    populationImpactedEstimate: 9200,
    liveWaterLevelCm: 50,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-65',
    name: 'Rahate Colony T-Point & Wardha Road Link Channel',
    marathiName: 'रहाटे कॉलनी टी-पॉइंट व वर्धा रोड लिंक नाला',
    zone: 'Dhantoli (Zone 4)',
    wardNo: 'Ward 17',
    lat: 21.1295,
    lng: 79.0762,
    category: 'Bridge / Flyover Approach',
    baseRisk: 'normal',
    elevationMeters: 304,
    vulnerabilityFactor: 'Flyover down-ramp storm channels require manual clearing during peak downpours',
    historicalEvent: 'Temporary 1 ft water on slow lane, cleared within 30 min',
    drainageCapacity: '82%',
    nearestNDRFPost: 'Civil Lines Station (2.0 km)',
    emergencyHelpline: '0712-2567014',
    nodalContact: 'Smt. Kavita Patil (EE Dhantoli)',
    evacuationShelter: 'Neurological Institute Ground Auditorium',
    populationImpactedEstimate: 4800,
    liveWaterLevelCm: 20,
    cctvStreamAvailable: true,
  },

  // 66-77: Outer Suburbs, Ring Road Interchanges & Reservoir Outflows
  {
    id: 'HOT-66',
    name: 'Somalwada Square & Manish Nagar Railway Crossing',
    marathiName: 'सोमलवाडा चौक व मनीष नगर रेल्वे क्रॉसिंग',
    zone: 'Laxmi Nagar (Zone 1)',
    wardNo: 'Ward 36',
    lat: 21.0985,
    lng: 79.0745,
    category: 'Underpass Waterlogging',
    baseRisk: 'severe',
    elevationMeters: 298,
    vulnerabilityFactor: 'Manish Nagar RUB underpass floods during heavy cloudbursts',
    historicalEvent: 'Cars submerged up to roof level; automatic barricades lowered to prevent entry',
    drainageCapacity: '55%',
    nearestNDRFPost: 'Sonegaon Station (1.2 km)',
    emergencyHelpline: '0712-2567011',
    nodalContact: 'Shri Aniket Rane (EE Laxmi Nagar)',
    evacuationShelter: 'Manish Nagar Samaj Bhavan',
    populationImpactedEstimate: 16000,
    liveWaterLevelCm: 150,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-67',
    name: 'Jaitala Old Village Nallah & Bazar Ward',
    marathiName: 'जयताळा जुने गाव नाला व बाजार वॉर्ड',
    zone: 'Laxmi Nagar (Zone 1)',
    wardNo: 'Ward 38',
    lat: 21.1082,
    lng: 79.0315,
    category: 'Low-lying Residential',
    baseRisk: 'moderate',
    elevationMeters: 308,
    vulnerabilityFactor: 'High-velocity flow from MIDC Hingna hills converging on village houses',
    historicalEvent: 'Road collapsed near bridge culvert; water entered 150 homes',
    drainageCapacity: '65%',
    nearestNDRFPost: 'MIDC Hingna Station (1.8 km)',
    emergencyHelpline: '0712-2567011',
    nodalContact: 'Shri Aniket Rane (EE Laxmi Nagar)',
    evacuationShelter: 'Jaitala ZP High School',
    populationImpactedEstimate: 6800,
    liveWaterLevelCm: 52,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-68',
    name: 'Bhamti - Parsodi Canal Siphon & Ring Road Crossing',
    marathiName: 'भामटी - परसोडी कालवा सायफन व रिंग रोड',
    zone: 'Laxmi Nagar (Zone 1)',
    wardNo: 'Ward 37',
    lat: 21.1125,
    lng: 79.0412,
    category: 'Reservoir / Canal Discharge',
    baseRisk: 'moderate',
    elevationMeters: 306,
    vulnerabilityFactor: 'Canal siphon structure prone to silt blockage during intense monsoon flow',
    historicalEvent: 'Backwater flooded surrounding residential apartments ground floors',
    drainageCapacity: '70%',
    nearestNDRFPost: 'VNIT Disaster Post (1.8 km)',
    emergencyHelpline: '0712-2567011',
    nodalContact: 'Shri Aniket Rane (EE Laxmi Nagar)',
    evacuationShelter: 'Bhamti Community Bhavan',
    populationImpactedEstimate: 5900,
    liveWaterLevelCm: 44,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-69',
    name: 'Trimurti Nagar - NIT Layout Low Trench',
    marathiName: 'त्रिमूर्ती नगर - एनआयटी लेआउट सखल भाग',
    zone: 'Laxmi Nagar (Zone 1)',
    wardNo: 'Ward 38',
    lat: 21.1215,
    lng: 79.0452,
    category: 'Low-lying Residential',
    baseRisk: 'normal',
    elevationMeters: 308,
    vulnerabilityFactor: 'Local road gradient slopes inward toward colony center',
    historicalEvent: 'Temporary water accumulation; clears via underground pipeline within 1 hour',
    drainageCapacity: '80%',
    nearestNDRFPost: 'VNIT Disaster Post (1.2 km)',
    emergencyHelpline: '0712-2567011',
    nodalContact: 'Shri Aniket Rane (EE Laxmi Nagar)',
    evacuationShelter: 'Trimurti Nagar NIT Garden Pavilion',
    populationImpactedEstimate: 4200,
    liveWaterLevelCm: 20,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-70',
    name: 'Pande Layout & Khamla Nallah Culvert No. 3',
    marathiName: 'पांडे लेआउट व खामला नाला कल्व्हर्ट क्र. ३',
    zone: 'Laxmi Nagar (Zone 1)',
    wardNo: 'Ward 37',
    lat: 21.1192,
    lng: 79.0585,
    category: 'River / Waterbody Overflow',
    baseRisk: 'moderate',
    elevationMeters: 305,
    vulnerabilityFactor: 'Enclosed RCC box culvert experiences hydraulic pressure during flash downpour',
    historicalEvent: 'Manhole covers pushed open by water pressure; warning cones placed',
    drainageCapacity: '72%',
    nearestNDRFPost: 'VNIT Disaster Post (1.0 km)',
    emergencyHelpline: '0712-2567011',
    nodalContact: 'Shri Aniket Rane (EE Laxmi Nagar)',
    evacuationShelter: 'Pande Layout Samaj Bhavan',
    populationImpactedEstimate: 5100,
    liveWaterLevelCm: 38,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-71',
    name: 'Ayodhya Nagar & Omkar Nagar Ring Road Dip',
    marathiName: 'अयोध्या नगर व ओंकार नगर रिंग रोड',
    zone: 'Hanuman Nagar (Zone 3)',
    wardNo: 'Ward 30',
    lat: 21.1085,
    lng: 79.1125,
    category: 'Low-lying Residential',
    baseRisk: 'moderate',
    elevationMeters: 297,
    vulnerabilityFactor: 'Runoff from elevated Ring Road collects in lower housing societies',
    historicalEvent: 'Water logged up to 2 ft; municipal suction tankers deployed',
    drainageCapacity: '66%',
    nearestNDRFPost: 'Sakkardara Station (1.8 km)',
    emergencyHelpline: '0712-2567013',
    nodalContact: 'Shri Suresh Khare (EE Hanuman Nagar)',
    evacuationShelter: 'Ayodhya Nagar High School',
    populationImpactedEstimate: 7200,
    liveWaterLevelCm: 48,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-72',
    name: 'Shatabdi Nagar Chowk & Pora Basin Connector',
    marathiName: 'शताब्दी नगर चौक व पोरा खोरे जोड नाला',
    zone: 'Hanuman Nagar (Zone 3)',
    wardNo: 'Ward 31',
    lat: 21.0998,
    lng: 79.0885,
    category: 'River / Waterbody Overflow',
    baseRisk: 'severe',
    elevationMeters: 296,
    vulnerabilityFactor: 'Pora river tributary overflow across arterial connection to Wardha road',
    historicalEvent: 'Road barricaded; 2 wheelers washed into side ditch during heavy flow',
    drainageCapacity: '52%',
    nearestNDRFPost: 'Manewada Sub-Station (1.6 km)',
    emergencyHelpline: '0712-2567013',
    nodalContact: 'Shri Suresh Khare (EE Hanuman Nagar)',
    evacuationShelter: 'Shatabdi Nagar Community Center',
    populationImpactedEstimate: 9400,
    liveWaterLevelCm: 98,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-73',
    name: 'Babulban & Garoba Maidan Nallah Confluence',
    marathiName: 'बाबुलबन व गरोबा मैदान नाला संगम',
    zone: 'Lakadganj (Zone 8)',
    wardNo: 'Ward 24',
    lat: 21.1482,
    lng: 79.1352,
    category: 'Slum / Riverbank Settlement',
    baseRisk: 'severe',
    elevationMeters: 298,
    vulnerabilityFactor: 'High density hutments located on low embankment of storm nallah',
    historicalEvent: 'Rescue teams deployed inflatable boats to shift 80 families',
    drainageCapacity: '48%',
    nearestNDRFPost: 'Lakadganj Fire Outpost (1.0 km)',
    emergencyHelpline: '0712-2567018',
    nodalContact: 'Smt. Priya Channe (EE Lakadganj)',
    evacuationShelter: 'Babulban Urdu High School',
    populationImpactedEstimate: 8300,
    liveWaterLevelCm: 110,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-74',
    name: 'Pardi Cement Road - Kapsi Border Low Creek',
    marathiName: 'पारडी सिमेंट रोड - कापसी सीमा नाला',
    zone: 'Lakadganj (Zone 8)',
    wardNo: 'Ward 26',
    lat: 21.1412,
    lng: 79.1785,
    category: 'Industrial / Highway Corridor',
    baseRisk: 'severe',
    elevationMeters: 292,
    vulnerabilityFactor: 'Transport warehouse hub with unpaved truck parking creating massive mud dams',
    historicalEvent: 'NH-53 interstate corridor traffic halted due to water sheet crossing 3.5 ft',
    drainageCapacity: '45%',
    nearestNDRFPost: 'Kalamna Fire Station (4.0 km)',
    emergencyHelpline: '0712-2567018',
    nodalContact: 'Smt. Priya Channe (EE Lakadganj)',
    evacuationShelter: 'Kapsi Transport Association Bhavan',
    populationImpactedEstimate: 11000,
    liveWaterLevelCm: 125,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-75',
    name: 'Kalmeshwar Road - Gondkhairi Nallah Approach',
    marathiName: 'कळमेश्वर रोड - गोंडखैरी नाला परिसर',
    zone: 'Rural / Western Metropolitan',
    wardNo: 'Kalmeshwar Division',
    lat: 21.2312,
    lng: 78.9185,
    category: 'Bridge / Flyover Approach',
    baseRisk: 'moderate',
    elevationMeters: 320,
    vulnerabilityFactor: 'Rural highway bridge approaches submerged during rapid hillside cloudburst',
    historicalEvent: 'State highway traffic diverted via Katol for 8 hours',
    drainageCapacity: '62%',
    nearestNDRFPost: 'Kalmeshwar Fire Post (2.0 km)',
    emergencyHelpline: '0712-2567030',
    nodalContact: 'Shri Milind Deshmukh (EE PWD Rural)',
    evacuationShelter: 'Gondkhairi Gram Panchayat Hall',
    populationImpactedEstimate: 4600,
    liveWaterLevelCm: 45,
    cctvStreamAvailable: false,
  },
  {
    id: 'HOT-76',
    name: 'Umred Road - Dighori Toll Nallah Low Basin',
    marathiName: 'उमरेड रोड - दिघोरी टोल नाका सखल भाग',
    zone: 'Nehru Nagar (Zone 5)',
    wardNo: 'Ward 29',
    lat: 21.0912,
    lng: 79.1485,
    category: 'Industrial / Highway Corridor',
    baseRisk: 'moderate',
    elevationMeters: 294,
    vulnerabilityFactor: 'Highway widening work with half-constructed median stormwater lines',
    historicalEvent: 'Toll plaza lanes inundated; toll collection temporarily suspended',
    drainageCapacity: '65%',
    nearestNDRFPost: 'Sakkardara Rescue Base (3.5 km)',
    emergencyHelpline: '0712-2567015',
    nodalContact: 'Shri Anand Mankar (EE Nehru Nagar)',
    evacuationShelter: 'Dighori Toll Administrative Block',
    populationImpactedEstimate: 5800,
    liveWaterLevelCm: 50,
    cctvStreamAvailable: true,
  },
  {
    id: 'HOT-77',
    name: 'Khaparkheda Power Plant Canal Sluice & River Confluence',
    marathiName: 'खापरखेडा वीज प्रकल्प कालवा सांडवा व नदी संगम',
    zone: 'Rural / Northern Metropolitan',
    wardNo: 'Khaparkheda Town',
    lat: 21.2845,
    lng: 79.1215,
    category: 'Reservoir / Canal Discharge',
    baseRisk: 'severe',
    elevationMeters: 295,
    vulnerabilityFactor: 'High-volume cooling water canal discharge combined with monsoon river backflow',
    historicalEvent: 'Alert sirens sounded; precautionary sandbagging on power station boundary wall',
    drainageCapacity: '50%',
    nearestNDRFPost: 'Khaparkheda Emergency Disaster Unit (0.8 km)',
    emergencyHelpline: '0712-2567030',
    nodalContact: 'Shri Milind Deshmukh (EE PWD Rural)',
    evacuationShelter: 'Khaparkheda Thermal Power High School Auditorium',
    populationImpactedEstimate: 12500,
    liveWaterLevelCm: 135,
    cctvStreamAvailable: true,
  },
];

/**
 * Calculates dynamic risk level for each hotspot based on chosen day's precipitation forecast.
 */
export function calculateDynamicHotspotRisk(
  hotspot: RiskHotspot,
  dayForecast: DayForecast
): { currentRisk: RiskLevel; waterLevelEstCm: number; warningText: string } {
  const precip = dayForecast.precipitationMm;
  const prob = dayForecast.precipitationProbability;

  // Severe rain (>40mm or alert RED)
  if (precip >= 40 || dayForecast.alertLevel === 'RED') {
    if (hotspot.baseRisk === 'severe') {
      return {
        currentRisk: 'severe',
        waterLevelEstCm: Math.min(200, (hotspot.liveWaterLevelCm || 100) + Math.round(precip * 1.5)),
        warningText: 'FLASH FLOOD EMERGENCY: Imminent breach / waterlogging depth >1.2m',
      };
    } else if (hotspot.baseRisk === 'moderate') {
      return {
        currentRisk: 'severe',
        waterLevelEstCm: Math.min(140, (hotspot.liveWaterLevelCm || 50) + Math.round(precip * 1.2)),
        warningText: 'HIGH RISK: Water accumulation anticipated >75cm',
      };
    } else {
      return {
        currentRisk: 'moderate',
        waterLevelEstCm: Math.min(60, (hotspot.liveWaterLevelCm || 20) + Math.round(precip * 0.8)),
        warningText: 'MONITORING: Waterlogging watch on low street sections',
      };
    }
  }

  // Moderate rain (15mm - 40mm or alert ORANGE)
  if (precip >= 15 || dayForecast.alertLevel === 'ORANGE') {
    if (hotspot.baseRisk === 'severe') {
      return {
        currentRisk: 'severe',
        waterLevelEstCm: Math.min(130, (hotspot.liveWaterLevelCm || 80) + Math.round(precip * 1.1)),
        warningText: 'SEVERE WATCH: High waterlogging risk along natural drains',
      };
    } else if (hotspot.baseRisk === 'moderate') {
      return {
        currentRisk: 'moderate',
        waterLevelEstCm: Math.min(80, (hotspot.liveWaterLevelCm || 40) + Math.round(precip * 0.9)),
        warningText: 'MODERATE RISK: Water accumulation expected on road shoulders',
      };
    } else {
      return {
        currentRisk: 'normal',
        waterLevelEstCm: Math.min(30, (hotspot.liveWaterLevelCm || 15) + Math.round(precip * 0.4)),
        warningText: 'NORMAL CONDITIONS: Standard runoff drainage operational',
      };
    }
  }

  // Light rain (5mm - 15mm or alert YELLOW)
  if (precip >= 5 || prob >= 50) {
    if (hotspot.baseRisk === 'severe') {
      return {
        currentRisk: 'moderate',
        waterLevelEstCm: Math.min(75, (hotspot.liveWaterLevelCm || 50) + 15),
        warningText: 'WATCH ALERT: Minor ponding possible in low-lying pockets',
      };
    } else {
      return {
        currentRisk: 'normal',
        waterLevelEstCm: Math.min(25, (hotspot.liveWaterLevelCm || 15) + 5),
        warningText: 'NORMAL: Mild precipitation, no disruption expected',
      };
    }
  }

  // Dry / Normal (<5mm)
  return {
    currentRisk: hotspot.baseRisk === 'severe' && dayForecast.dayIndex === 0 ? 'moderate' : 'normal',
    waterLevelEstCm: Math.min(15, (hotspot.liveWaterLevelCm || 10) * 0.2),
    warningText: 'NORMAL CONDITIONS: Clear drainage channels, dry roads',
  };
}

/**
 * Fallback 7-Day Weather Forecast Data for Nagpur (Lat: 21.1458, Long: 79.0882).
 * Used instantly and synchronized with Open-Meteo live API.
 */
export const DEFAULT_7DAY_NAGPUR_FORECAST: DayForecast[] = [
  {
    dayIndex: 0,
    dateString: 'Today, 16 Aug',
    dayName: 'Today',
    tempMax: 31,
    tempMin: 24,
    weatherCode: 65,
    weatherDescription: 'Heavy Monsoon Showers & Thunderstorm',
    precipitationProbability: 88,
    precipitationMm: 54.2,
    windSpeedKmh: 28,
    humidityPercent: 92,
    alertLevel: 'ORANGE',
    alertTitle: 'ORANGE ALERT: Heavy Rainfall & Urban Flooding Risk in Next 3 Hours',
    alertDetails:
      'Nagpur Municipal Corporation (NMC) Disaster Management Cell issues Orange Alert. Intense cloudburst over Dharampeth, Lakadganj, and Pili River catchment. Avoid low underpasses.',
    aqi: 42,
    aqiCategory: 'Good',
  },
  {
    dayIndex: 1,
    dateString: 'Tomorrow, 17 Aug',
    dayName: 'Mon',
    tempMax: 29,
    tempMin: 23,
    weatherCode: 82,
    weatherDescription: 'Continuous Heavy Downpour & Gusty Winds',
    precipitationProbability: 95,
    precipitationMm: 72.8,
    windSpeedKmh: 34,
    humidityPercent: 96,
    alertLevel: 'RED',
    alertTitle: 'RED ALERT: Severe Flood Watch across Nag & Pili River Corridors',
    alertDetails:
      'Extreme rainfall exceeding 70mm forecast. SDRF & NDRF teams placed on high readiness at VNIT & Kalamna. Citizen helpline 0712-2567011 activated 24x7.',
    aqi: 38,
    aqiCategory: 'Good',
  },
  {
    dayIndex: 2,
    dateString: 'Tue, 18 Aug',
    dayName: 'Tue',
    tempMax: 30,
    tempMin: 24,
    weatherCode: 63,
    weatherDescription: 'Moderate Rain with Intermittent Spells',
    precipitationProbability: 70,
    precipitationMm: 28.4,
    windSpeedKmh: 22,
    humidityPercent: 88,
    alertLevel: 'YELLOW',
    alertTitle: 'YELLOW ALERT: Waterlogging Watch on Low-lying Arteries',
    alertDetails:
      'Intermittent showers expected. Sonegaon Lake, Narendra Nagar Underpass, and Pardi Flyover under regular municipal pump monitoring.',
    aqi: 45,
    aqiCategory: 'Good',
  },
  {
    dayIndex: 3,
    dateString: 'Wed, 19 Aug',
    dayName: 'Wed',
    tempMax: 32,
    tempMin: 25,
    weatherCode: 61,
    weatherDescription: 'Scattered Light Rain & Overcast Skies',
    precipitationProbability: 45,
    precipitationMm: 12.0,
    windSpeedKmh: 18,
    humidityPercent: 82,
    alertLevel: 'YELLOW',
    alertTitle: 'YELLOW ALERT: Scattered Showers in Outer Suburbs',
    alertDetails:
      'Light to moderate showers localized in Kamptee, Hingna, and Umred road sectors. No widespread flood threat.',
    aqi: 52,
    aqiCategory: 'Moderate',
  },
  {
    dayIndex: 4,
    dateString: 'Thu, 20 Aug',
    dayName: 'Thu',
    tempMax: 33,
    tempMin: 25,
    weatherCode: 3,
    weatherDescription: 'Passing Clouds & Humid Conditions',
    precipitationProbability: 25,
    precipitationMm: 3.5,
    windSpeedKmh: 14,
    humidityPercent: 76,
    alertLevel: 'GREEN',
    alertTitle: 'GREEN ALERT: Normal Conditions across All 10 NMC Zones',
    alertDetails:
      'Favorable weather. Draining of residual stagnation progressing swiftly across low-lying layouts.',
    aqi: 60,
    aqiCategory: 'Moderate',
  },
  {
    dayIndex: 5,
    dateString: 'Fri, 21 Aug',
    dayName: 'Fri',
    tempMax: 34,
    tempMin: 26,
    weatherCode: 2,
    weatherDescription: 'Partly Cloudy with Warm Afternoon',
    precipitationProbability: 15,
    precipitationMm: 1.2,
    windSpeedKmh: 12,
    humidityPercent: 70,
    alertLevel: 'GREEN',
    alertTitle: 'GREEN ALERT: Normal Weather & Dry Road Corridors',
    alertDetails: 'Dry spells across Vidarbha region. All 77 hotspots operating at normal baseline safety.',
    aqi: 68,
    aqiCategory: 'Moderate',
  },
  {
    dayIndex: 6,
    dateString: 'Sat, 22 Aug',
    dayName: 'Sat',
    tempMax: 35,
    tempMin: 26,
    weatherCode: 1,
    weatherDescription: 'Mainly Clear & Sunny Sky',
    precipitationProbability: 10,
    precipitationMm: 0.0,
    windSpeedKmh: 10,
    humidityPercent: 65,
    alertLevel: 'GREEN',
    alertTitle: 'GREEN ALERT: Clear Sky & Normal Operations',
    alertDetails:
      'No weather alerts in force for Nagpur district. Municipal desilting teams carrying out scheduled channel maintenance.',
    aqi: 74,
    aqiCategory: 'Moderate',
  },
];
